### ISSUE TITLE
US9 Connection with MongoDB Atlas

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#16]
## Value Proposition

As a user
I want to save my data in a cloud database 
So that I can access my player list from different devices
​

## Description

Connection with MongDB Atlas
​

## Acceptance Criteria

- [ ] After changing the entries in the player list, the changes are still present when the list is opened in another browser
      ​

## Tasks

- [ ] Create a feature branch
- [ ] Create a DB in mongoDB Atlas
- [ ] Install `mongoose` and adapt `.env.local`
- [ ] Create a `db/connect.js` file and fill it
- [ ] Write a Schema
- [ ] Write a request handler in the Next.js API route for the different methods
- [ ] Adapt the functions `handleSave`, `handleChangeComment` and `deletePlayer`

**Comment by DErdmann1** [comment]
Nice, have fun with the connection :)
