### ISSUE TITLE
US2 Create a dummy player

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#2]
## Value Proposition

As a user
I want to add Bundesliga players from season 2021 or 2022 to my player list
So that I can expand the list of players, that interest me
​

## Description

<img width="552" alt="Scribble US2" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/e61df698-0648-43dc-a49e-7a14dcd086f7">

## Acceptance Criteria

- [x] A form is displayed
- [x] The player name can be entered in a free search field with a minimum of 4 characters
- [x] The team and season can be chosen from mandatory dropdown menus
- [x] After pressing "Create Player" the updated list with the new player name is displayed
      ​

## Tasks

- [x] Create a feature branch
- [x] Create a form component with 3 input fields/labels and a submit button
- [x] Add the data for the dropdown menus, use the Bundesliga and the seasons 2021 and 2022 as a starting point. Source for team data: [API-FOOTBALL](https://www.api-football.com/)
- [x] Import the form component to pages/index.js
- [x] Create a state for the player list
- [x] Add functionality to the submit button: a new player object with the submitted data is added to the player list state
- [x] Check that the new player object includes the player name, team id and season 
- [x] Submitting the form should redirect the user to the list page, where the list with the name of the new player is displayed

**Comment by ekat-br** [comment]
Hi Frank, I think your user story is well structured and understandable. A few comments and questions: 

- How do you ensure that the dropdown includes the correct teams and seasons? I can't understand where you get the data from.
- Is all data required when submitting the form data? Maybe you can add this point as a task or/and as an acceptance criteria. 
- When submitting the data, is it expected to see the new player in the list page? Or is this part of another US? I'm asking because of the image you provided. If so, make sure to add the acceptance criteria that the submitted player is correctly displayed. I don't understand why you write 'the updated list with 4 players is visible'. Why exactly 4 players?

**Comment by Frank-Schaeske** [comment]
Hi Katja, many thanks for your feedback. I hope that my updated US answers your questions.
