### ISSUE TITLE
US10 Different statistics for players in different positions

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#20]
## Value Proposition

As a user
I want to see different stats depending on the position of a player
So that I can better evaluate his strengths
​

## Description

![Scribble US10](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/53ddf8ee-372c-4a66-a408-9fb0a42b453f)
​

## Acceptance Criteria

- [ ] For all players should be visible: name, photo, team, nationality, position, season and appearances 
- [ ] Additionally visible stats for goalkeepers: goals conceded and goal saves
- [ ] Additionally visible stats for defenders: duels total and duels won
- [ ] Additionally visible stats for midfielders and attackers: goals and assists
      ​

## Tasks

- [ ] Create a feature branch
- [ ] In the `PlayerDetails` component create a logic to display different stats depending on the position of the player

**Comment by CJAkkuec** [comment]
> Create a feature branch

I think it'd be beneficial to include the name of the branch as well. 👍 

> In the PlayerDetails component create a logic to display different stats depending on the position of the player

The 'a' before logic is redundant. I think rather than state that creating logic is required, perhaps allude to how this may be handled, such as:
- [ ] implement conditional rendering based on player positions

**Comment by Frank-Schaeske** [comment]
Thanks for your comment CJ! I've updated my US accordingly.
