### ISSUE TITLE
US11 Filter the player list by position

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#21]
## Value Proposition

As a user
I want to be able to filter the player list by position
So that I can view my saved goalkeepers, defenders, midfielders or attackers separately
​

## Description

![Scribble US11](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/b1815a36-3ea3-4911-a16f-4e93dbb49eec)

## Acceptance Criteria

- [ ] Five radio buttons are visible
- [ ] It is possible to choose all players and in this case all players are visible
- [ ] It is possible to choose only goalkeepers and afterwards only goalkeepers are visible
- [ ] It is possible to choose only defenders and afterwards only defenders are visible
- [ ] It is possible to choose only midfielders and afterwards only midfielders are visible
- [ ] It is possible to choose only attackers and afterwards only attackers are visible
      ​

## Tasks

- [ ] Create a feature branch
- [ ] Create a new component `PlayerFilterByPosition`
- [ ] Set up a state variable to hold the filtered position
- [ ] Create a filter function
- [ ] Render the data depending on the filter position

**Comment by CJAkkuec** [comment]
> Create a new component PlayerFilter**ed**ByPosition

🤓

**Comment by Frank-Schaeske** [comment]
Thanks for your comment CJ! However, I'm unsure if the renaming really makes sense, since the component is actually the filter.

**Comment by CJAkkuec** [comment]
I see 🤔 I'm not sure where you are at right now in terms of your app architecture, but are you handling the filtering of players and a general player overview on different pages? 

Either way, if `PlayerFilterByPosition` is the component that lets the user select the position to filter for, I'd probably even argue it should be `PositionRadioButtons`. Something like `PlayerFilterByPosition` would be a more apt name for a derived state variable. Although I'd probably go for something like this, maybe ...

```js

const [position, setPosition] = useState("");

//fancy radio buttons component

const filteredPlayers = //fancy filter function

return (

{filteredPlayers.map(//fancy mapping)}

)
```
