### ISSUE TITLE
US12 Search for players from the 2. Bundesliga

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#22]
## Value Proposition

As a user
I want to be able to search for players from the 2. Bundesliga as well
So that I can add interesting players from this league to my player list
​

## Description

![Scribble US12](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/6ad93c52-c36a-4fb4-bd0f-f379e48f5621)
​

## Acceptance Criteria

- [ ] An additional dropdown menu for the league is available
- [ ] The season dropdown menu offers the options `2022/23`, `2021/22` and `2020/21`   
- [ ] The league dropdown menu offers the options `Bundesliga` and `2. Bundesliga` 
- [ ] The options for the team dropdown menu depend on the selections for season and league and represent the league composition in the selected year
      ​

## Tasks

- [ ] Create a feature branch `feature/add-bundesliga-2`
- [ ] Implement conditional options for the team dropdown menu depending on the selected options for season and league

**Comment by CJAkkuec** [comment]
Hey, it's me again 👋 

I have a question rather than a point of critique, but take it with a grain of salt since I know close to nothing about the ball of foot.

Would the selection process not be the following:

1. Season Selection
2. League Selection
3. Team Selection
4. Player Selection (rather than an input field)

... because 1 informs 2 informs 3 informs 4. Right?

If you keep it as an input field, user inputs may actually make searching a little more difficult due to spelling errors/etc.

**Comment by Frank-Schaeske** [comment]
Hi CJ,

that's a very good question/remark and in principle you are right! 

However, you have to remember that teams can easily have a squad of 30 players. Therefore, I think that the input field is more convenient for users than another dropdown menu with so many options. I'd rather risk the spelling errors/etc.

**Comment by CJAkkuec** [comment]
That makes sense! Perhaps it might be beneficial to still consider the order of selections I suggested and have the input "search" field at the end respond with an auto-complete? That way you could still cascade your information and not have some pretty expensive calculation right at the top (e.g. parsing 30 players * XY teams * 2 leagues * XY seasons).

**Comment by Frank-Schaeske** [comment]
Good idea to change the order of selections, but at the moment I won't use an auto-complete, as the data is not available for me (I fetch an external API with the input from the search field and implementing all squads in my App would be too much effort in the limited time available, especially if I want to add more leagues later).

**Comment by CJAkkuec** [comment]
Sounds good, thank you for considering my suggestions. :)
