### ISSUE TITLE
US13 Modal to confirm deletion

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#25]
## Value Proposition

As a user
I want to be able to confirm my action after hitting the `Delete Player` button
So that I can avoid accidental deletion
​

## Description

![Scribble US13](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/3695890a-d269-4423-a0fe-ac5fc3e187ba)

## Acceptance Criteria

- [x] After hitting the `Delete Player` button a modal opens
- [x] The user is asked to confirm the deletion
- [x] Two buttons `Delete` and `Cancel` are visible 
- [x] Hitting `Delete` closes the modal and redirects the user to the player list view where the deleted player is missing
- [x] Hitting `Cancel` closes the modal and redirects the user back to the player details view
      ​

## Tasks

- [x] Create a feature branch `feature/confirm-deletion`
- [x] Create a state variable to control the visibility of the modal
- [x] Add a confirmation modal and style it
- [x] Implement the logic to show/hide the modal and handle the delete action

**Comment by Kheirah** [comment]
In case you're not opposed to `react-modal`, you may use that package for creating the modal. It's an accessible piece and easy to use.
But you can build your own modal, too of course.
