### ISSUE TITLE
US14 Modal for duplicate avoidance

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#28]
## Value Proposition

As a user
I want to be notified if a player/season combination is already saved in my list
So that I can avoid duplicates
​

## Description

![Scribble US14](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/d681ab2a-ce65-47cc-a41e-317615dd2293)

​

## Acceptance Criteria

- [ ] After searching for a player/season combination, that is already saved in the player list, a modal opens
- [ ] The user gets the message "The searched player is already saved for this season. "
- [ ] Two buttons `New Search` and `View Player` are visible 
- [ ] Hitting `New Search` closes the modal so that the user can search again 
- [ ] Hitting `View Player` closes the modal and redirects the user to the details view for the searched player
      ​

## Tasks

- [ ] Create a feature branch `feature/duplicate-avoidance`
- [ ] Create state variables to control the visibility of the modal and overlay
- [ ] Add a modal and a overlay and style them
- [ ] Implement the logic to compare the searched player/season combination with the database entries and trigger the modal if there is a match
- [ ] Implement the logic for the `View Player` button to redirect to the correct player details page
