### ISSUE TITLE
US3 Fetch API and show the number of goals

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#3]
## Value Proposition

As a user
I want to search for Bundesliga players from season 2021 or 2022
So that I can see how many goals they scored in the respective season
​

## Description

<img width="564" alt="Scribble US3" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/9ac5ede1-eb18-4a0c-b170-37d221aaec92">
​

## Acceptance Criteria

- [ ] After entering player name, team and season a player details page is visible
- [ ] The player details include the number of goals in the respective season as additional information
- [ ] If no player is found a message "no player found with this name" is displayed
      ​

## Tasks

- [ ] Create a feature branch
- [ ] Fetch the API with the submitted "team", "season" and "search" as part of the URL
- [ ] Create a file add.js in the pages folder
- [ ] Create a component "PlayerDetails" and import it on the new page
- [ ] Render the "PlayerDetails" component with the fetched data

**Comment by oliverhees** [comment]
Hey Frank,

great work!
Its look good for me :)
