### ISSUE TITLE
US15 Ranking of saved players

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#30]
## Value Proposition

As a user
I want to be able to see how good the stats of a player are compared to other saved players in the same position
So that I can better evaluate that player
​

## Description

![Scribble US15](https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/37b782a0-9ba0-47fd-9644-63e88183441a)

​

## Acceptance Criteria

- [ ] The player details view has a `Compare Player` link
- [ ] Hitting `Compare Player` opens a new page
- [ ] The new page displays a short description of the ranking 
- [ ] Goalkeepers are ranked by conceded goals (low to high)
- [ ] Defenders are ranked by duel rate (high to low)
- [ ] Midfielders and Attackers are ranked by scorer points (high to low)
- [ ] The new page has a `Back` link that redirects to the player details
      ​

## Tasks

- [ ] Create a feature branch `feature/player-ranking`
- [ ] Create a new page `pages/players/[id]/ranking.js` with a `Back` link to `pages/players/[id]/index.js`
- [ ] Add a `Compare Player` link from `pages/players/[id]/index.js` to `pages/players/[id]/ranking.js`
- [ ] Implement the logic to render the headline and the player ranking based on the position of the original player

**Comment by mbosselmann** [comment]
Hi Frank,
LGTM! 🦊
