### ISSUE TITLE
US4 Add a player to the player list or start a new search

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#4]
## Value Proposition

As a user
I want to be able to save found players to my player list or start a new search
So that I can expand the list of players, that interest me
​

## Description

<img width="925" alt="Scribble US4" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/1820e811-4a97-4755-8492-9214d2b11a07">
​

## Acceptance Criteria

- [ ] Two fields `New Search` and `Save Player` are displayed after a successful search
- [ ] Hitting `New Search` redirects to the `homepage`
- [ ] Hitting `Save Player` redirects to a page, where the saved players are listed
- [ ] The list includes the player from the search 
      ​

## Tasks

- [ ] Create a feature branch
- [ ] Create a link to the `homepage`
- [ ] Create a button, that saves the player data and redirects to `players/index.js`
- [ ] Render the updated list with the new player on `players/index.js`

**Comment by HannesOster** [comment]
LGTM ;)
