### ISSUE TITLE
US5 Possibility to enter a comment about a found player

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#5]
## Value Proposition

As a user
I want to be able to enter a comment about a found player
So that I can save my observations in addition to the shown data
​

## Description

<img width="567" alt="Scribble US5" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/b086a28d-c116-4e32-9d22-a02d3f1f49eb">

## Acceptance Criteria

- [ ] A comment about a found player can be entered
- [ ] Hitting `Save Player` redirects to a page, where the saved players are listed
- [ ] The list includes the player from the search
- [ ] Hitting `New Search` redirects to the `homepage`
      ​

## Tasks

- [ ] Create a feature branch
- [ ] Create a form with a `<label>` and `<textarea>` 
- [ ] Use `Save Player` as submit button
- [ ] Render the updated list with the new player after submitting
- [ ] Check that the new player object in the list includes the entered comment

**Comment by HannesOster** [comment]
LGTM
