### ISSUE TITLE
US6 View details of players from the list

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#6]
## Value Proposition

As a user
I want to be able to see the details of the players in my list
So that I can check their statistics and read my comment
​

## Description

<img width="565" alt="Scribble US6" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/be6a0688-4187-4791-945e-fb49cb428854">
​

## Acceptance Criteria

- [ ] Clicking on a player name opens a new page
- [ ] The new page shows the details of the corresponding player including a (filled or empty) comment field
- [ ] `Edit Player` and `Delete Player` are visible, but have no functionality
      ​

## Tasks

- [ ] Create a new page `players/[id]/index.js`
- [ ] Make sure that the details of the player with the correct id are rendered
- [ ] Implement two links without functionality for `Edit Player` and `Delete Player`

**Comment by Roland-Hufnagel** [comment]
Hey Frank, I like this userstory. Good job! Only two things:
- Since a button without functionality has no value for the user (it's not part of your value proposition) it has to be removed here.
- So the last task is obsolete. Instead it maybe a good idea to change the list-items to be a link that refers to the corresponding detailpage

**Comment by Frank-Schaeske** [comment]
Thank you for your input, Roland! I have updated my US accordingly.

**Comment by Roland-Hufnagel** [comment]
Looks good now!
