### ISSUE TITLE
US7 Edit or delete a player

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#7]
## Value Proposition

As a user
I want to be able to edit my player comments and delete players from my list
So that my player list contains only players that still interest me and my comments are up to date
​

## Description

<img width="1263" alt="Scribble US7" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/383a6db3-d5a0-474c-bdd0-ef5c9cbd7875">

## Acceptance Criteria

- [ ] Clicking `Edit Player` opens a new page where the comment can be changed
- [ ] Clicking `Delete Player` redirects the user to the list view, where the deleted player is no longer visible
- [ ] Clicking `Update Player` on the new page redirects the user to the list view, where the updated player is visible
- [ ] Clicking `Back` redirects the user to the former page
      ​

## Tasks

- [ ] Create a new page `players/[id]/edit.js` with a `Update Player` button and a `Back` link
- [ ] Add functionality to `Edit Player`: the new page opens, where the comment can be updated
- [ ] Focus the comment field for changes
- [ ] Make sure that clicking `Update Player` redirects the user to `players/index.js` and that the comment for that player is updated in the player object
- [ ] Make sure that clicking `Back` redirects the user to `players/[id]/index.js`

**Comment by Roland-Hufnagel** [comment]
Hi Frank, somethings are not clear to me. Maybe your wireframe is also not a good help (since I think clicking on a players name leads to the third frame but there is no arrow for that) You should refactor the wireframe to make functionality clearer.
And one thing is also not clear: The back-button! Will it lead to the homepage or to the page, you come from? I think you come from the details page so 'back' should lead back to the details page. Or maybe the name of the button should better be 'Cancel'?

**Comment by Roland-Hufnagel** [comment]
Oh sorry, I just saw, that 'back' should lead to ```players/[id]/index.js``` in your task. Forget the last point.

**Comment by Roland-Hufnagel** [comment]
And that's why I give you an approval in advance! ✅

**Comment by Frank-Schaeske** [comment]
Hi Roland, my idea was that I use a bold frame for the start of this US, but I guess it wasn't clear enough. I really like your suggestion to use 'Cancel' instead of 'Back'.
