### ISSUE TITLE
US8 Add a header and footer

### ISSUE THREAD

**Issue by Frank-Schaeske** [Frank-Schaeske/ScoutingHelper#8]
## Value Proposition

As a user
I want to have a header and a footer
So that I can navigate and see the name of the App I am using
​

## Description

<img width="504" alt="Scribble US8" src="https://github.com/Frank-Schaeske/ScoutingHelper/assets/133861448/c45aebf2-c383-4b36-969a-325c353f8493">
​

## Acceptance Criteria

- [ ] A header and a footer are visible on the starting page
- [ ] A header and a footer are visible on the list page
- [ ] Clicking on the magnifying glass in the footer redirects to the starting page
- [ ] Clicking on the list in the footer redirects to the starting page
      ​

## Tasks

- [ ] Create a `Header` component with the headline
- [ ] Create a `NavigationBar` component with a magnifying glass icon and a list icon
- [ ] Import the components on `pages/index.js`
- [ ] Import the components on `players/index.js`

**Comment by oliverhees** [comment]
Nice @Frank-Schaeske,
it´s look good for me. Good Work :)
